try {

    dosomething();

} catch (err) {
    console.log(err);
}
